name: Tests

on:
  push:
    branches:
    - "*"

jobs:
  contract-tests:
    name: Contract Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 18.x
        cache: 'yarn'
    - name: Install Hardhat
      run: yarn add --dev hardhat
    - name: Test Contracts
      run: npx hardhat test


  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: borales/actions-yarn@v3.0.0
      with: 
        env: 
          REACT_APP_MORALIS_APPLICATION_ID: ${{secrets.REACT_APP_MORALIS_APPLICATION_ID}}
          REACT_APP_MORALIS_SERVER_URL: ${{secrets.REACT_APP_MORALIS_SERVER_URL}}
        cmd: test
